from lib import *
####################################################################
############################# Square ###############################
####################################################################
model='tb'
n_spins=1
n_x=n_y=55
a=1.0

a1=a*np.array([1,0])
a2=a*np.array([0,1])
zero=np.array([0,0])
dimensions=[n_x,n_y]
basis=[a1,a2]
######### lattice & sites #########
mu=0.2571428571428571
orbitals=[zero]
n_orbitals=len(orbitals)
SO_spin=np.eye(n_spins)
SO_orbital=np.eye(n_orbitals)
SO_tensor=-mu*np.kron(SO_spin,SO_orbital)
############ hopping ##############
t=1.0
hop_links = [[t, 0, 0, [1,0]],
             [t, 0, 0, [0,1]]]
########### impurities #############
V=-1.3020408163265307
impurity_loc = [[0, 0]]
impurity_spin = np.arange(n_spins)
impurity_orb = np.arange(n_orbitals)
impurities = [V, impurity_loc, impurity_spin, impurity_orb]
############## Energy ###############
epsilon=0.1
omega_lim=10*t 
omegas=np.array([0],dtype=complex)+1.0j*epsilon