from lib import *
####################################################################
########################## Graphene ############################
####################################################################
mu = -3.57
t=1.0
a=1.0
a1=(a/2)*np.array([3,np.sqrt(3)])
a2=(a/2)*np.array([3,-np.sqrt(3)])
d1=(a/2)*np.array([1,np.sqrt(3)])
d2=(a/2)*np.array([1,-np.sqrt(3)])
d3=-a*np.array([1,0])
zero=np.array([0,0])
dimensions=[11,11,1]
n_dim=len(dimensions)
n_spins=1
n_orbitals=1
n_cells=np.prod(n_dim)
######### lattice & sites #########
lattice_basis=[a1,a2]
cell_basis=[d3]
site_spin=np.eye(n_spins)
site_orbital=np.eye(n_orbitals)
site_tensor_A=-mu*np.kron(site_spin,site_orbital)
site_tensor_B=site_tensor_A
site_tensors=[site_tensor_A, site_tensor_B]
############## hopping ##############
intracell_hopping=[[1,2]]
intercell_hopping=[[[1,2]],[[1,2]]]
intercell_PBC=[True,True]
hopping_spin=np.eye(n_spins)
hopping_orbital=np.eye(n_orbitals)
hopping_tensor=-t*np.kron(hopping_spin,hopping_orbital)
intracell_hopping=[hopping_tensor]
intercell_hopping=[[hopping_tensor],[hopping_tensor]]
############# constants ##############
n_sites=len(site_vectors)
n_atoms = n_cells*n_sites
dof = n_atoms*n_spins*n_orbitals
###################################################################
########################## Impurities #############################
###################################################################
V=1.21
impurity_locations=[[0,0]]
impurity_spin=np.eye(n_spins)
impurity_orbital=np.eye(n_orbitals)
impurity_tensor=V*np.kron(impurity_spin,impurity_orbital)
impurity_tensors=[impurity_tensor]
###################################################################
############################# Mean-field ##########################
###################################################################
Delta=0#1.32
SC_tensor=np.eye(n_spins*n_orbitals)
mean_field=Delta*Mean_field_all(SC_tensor, n_sites)
###################################################################
############################ Energy ###############################
###################################################################
Include_DOS=True
epsilon=0.1
omega_pts=401
omega_lim=10*t
# omegas=np.linspace(-omega_lim,omega_lim, omega_pts,endpoint=True,dtype=complex)+1.0j*epsilon
omegas=np.array([0],dtype=complex)+1.0j*epsilon
