from lib import *
####################################################################
########################## Graphene ############################
####################################################################
n_spins=2
n_x=n_y=41
a=1.0
a1=(a/2)*np.array([3,np.sqrt(3),0])
a2=(a/2)*np.array([3,-np.sqrt(3),0])
d3=0.5*np.array([-1,0,0])
zero=np.array([0,0,0])
dimensions=[n_x,n_y,1]
basis=[a1,a2]
######### lattice & sites #########
mu=-3.51
orbitals=[zero]
n_orbitals=len(orbitals)
SO_spin=np.eye(n_spins)
SO_orbital=np.eye(n_orbitals)
SO_tensor=-mu*np.kron(SO_spin,SO_orbital)
############ hopping ##############
t=1.0
hop_links = [[t, 0, 0, [1,0]],
             [t, 0, 0, [0,1]]]
########### impurities #############
V=1.21
impurity_loc = [[0, 0]]
impurity_spin = np.arange(n_spins)
impurity_orb = np.arange(n_orbitals)
impurities = [impurity_loc, impurity_spin, impurity_orb]
############# SC state ############

Delta=0.21
SC_spin=1.0j*Pauli_y
SC_orbital=Delta*np.eye(n_orbitals)
SC_tensor=np.kron(SC_spin,SC_orbital)
############## Energy ###############
epsilon=0.1
omega_pts=401
omega_lim=10*t 
omegas=np.linspace(-omega_lim,omega_lim,omega_pts,endpoint=True,dtype=complex)+1.0j*epsilon
# omegas=np.array([0],dtype=complex)+1.0j*epsilon