from lib import *
####################################################################
############################# Square ###############################
####################################################################
model='bdg_singlet_sc'
n_spins=2
n_x=21
n_y=21
n_z=16
a=1.0

a1=a*np.array([1,0,0])
a2=a*np.array([0,1,0])
a3=a*np.array([0,0,1])
zero=np.array([0,0,0])
dimensions=[n_x,n_y,n_z]
basis=[a1,a2,a3]
######### lattice & sites #########
mu=3.57
orbitals=[zero]
n_orbs=len(orbitals)
SO_spin=np.eye(n_spins)
SO_orbital=np.eye(n_orbs)
SO_tensor=-mu*np.kron(SO_spin,SO_orbital)
############ hopping ##############
t=1.0
hoppings = [[t, 0, 0, [1,0,0]],
             [t, 0, 0, [0,1,0]],
             [t, 0, 0, [0,0,1]]]
########### impurities #############
V=0
impurity_loc = [[0, 0, 0]]
impurity_spin = np.arange(n_spins)
impurity_orb = np.arange(n_orbs)
impurities = None #[V, impurity_loc, impurity_spin, impurity_orb]
########### Interaction ###############
U=2.8
U_orbs = np.eye(n_orbs)
U_spin = Pauli_x
hubbard_SO = -U*np.kron(U_spin, U_orbs)
#hubbard_tensor =[[hubbard_SO, [0,0,0]],
#                 [hubbard_SO, [1,0,0], True],
#                 [hubbard_SO, [0,1,0], True]]
#n_U=len(hubbard_tensor)
hubbard_U=np.kron(hubbard_SO, np.eye(n_x*n_y*n_z))
############ Mean-field #############
phi, Delta = 2.08833, 0.488416

hartree_SO = np.kron(np.diag([phi,phi]),np.eye(n_orbs))
initial_hartree = np.kron(hartree_SO, np.eye(n_x*n_y*n_z))
initial_hartree = np.diag(initial_hartree)

initial_fock = np.diag(np.zeros([n_x*n_y*n_z*n_spins*n_orbs]))

gorkov_SO = np.kron(np.array([[0,+Delta],[-Delta,0]]), np.eye(n_orbs))
initial_gorkov = np.kron(gorkov_SO, np.eye(n_x*n_y*n_z))

external_hartree = None
external_fock = None
external_gorkov= None
############## Energy ###############
epsilon=0.1
omega_lim=10*t 
omegas=np.array([0],dtype=complex)+1.0j*epsilon
######## Self-consistent param ########
friction=0
max_iterations=100
eps=0.001
T=0
