from lib import *
####################################################################
############################# Square ###############################
####################################################################
model='sc'
mu=-3.27
t=1.0
orbitals=[[0,0]]
n_orbs=len(orbitals)
n_spins=2
n_x=n_y=53
n_z=1
V=1.21
Delta=1.42
phi=.97
zeta=0.11
hubbard='nn_equal'
U=2.8
U_nn=1.2
U_nn_opp=0.8
T=0
friction=0.4
max_iterations=100
eps=0.001
