from lib import *
###################################################################
######################### Normal state ############################
###################################################################
n_spins=2
n_orbitals=1
n=5
n_x=n_y=n
mu=-2.67
s=0.0
delta=0.0
t=1.0

onsite_spin=-mu*np.eye(n_spins)#-phiUp*np.diag([1,0])-phiDown*np.diag([0,1])
onsite_orbital=np.eye(n_orbitals)#-s*Pauli_z+delta*Pauli_x
onsite_tensor=np.kron(onsite_spin,onsite_orbital)    

nn_spin=np.eye(n_spins)
nn_orbital=-t*np.eye(n_orbitals)
nn_tensor=np.kron(nn_spin,nn_orbital)

n_sites = n_x * n_y
dof = n_sites * n_spins * n_orbitals
###################################################################
########################## Impurities #############################
###################################################################
V=0#1.21
impurity_locations=[[0,0]] 
im_spin=np.eye(n_spins)
im_orbital=V*np.eye(n_orbitals)
impurity_tensor=np.kron(im_spin,im_orbital)
###################################################################
######################### Interaction #############################
###################################################################
U=2.8
U_orbital = np.eye(n_orbitals)
U_spin = Pauli_x
Hubbard_tensor = -U*np.kron(np.eye(n_sites), np.kron( U_spin, U_orbital))
###################################################################
######################### Mean-field ##############################
###################################################################
phiUp, phiDown, Delta= 0.4, 0.3, 0.5
Fock = np.zeros([n_x,n_y,n_spins,n_spins,n_orbitals,n_orbitals])

Hartree = np.zeros([n_x,n_y,n_spins,n_orbitals])

Hartree[:,:,0,:]=-phiUp*np.ones([n_x,n_y,n_orbitals])
Hartree[:,:,1,:]=-phiDown*np.ones([n_x,n_y,n_orbitals])

Gorkov= np.zeros([n_x,n_y,n_spins,n_spins,n_orbitals,n_orbitals])
Gorkov[:,:,0,1,:,:]=+Delta*np.ones([n_x,n_y,n_orbitals,n_orbitals])
Gorkov[:,:,1,0,:,:]=-Delta*np.ones([n_x,n_y,n_orbitals,n_orbitals])

friction=0.5
max_data_length=150
eps=0.001
T=0
###################################################################
############################ Energy ###############################
###################################################################
epsilon=0.1
omega_pts=401
omega_lim=10*t 
omegas=np.linspace(-omega_lim,omega_lim,omega_pts,endpoint=True,dtype=complex)+1.0j*epsilon