2 #n_spins
2 #n_orbitals
11 #n
-2.67 #mu
0.05 #s
0.075 #delta
1.0 #t
0 #V
[[0,0]] #impurity_locations
2.8 #U
0.85 #phi_up_plus
0.65 #phi_down_plus
0.8 #phi_up_minus
0.7 #phi_down_minus
1 #Delta
0.35 #varsigma
0 #friction
40 #max_iterations
0.01 #eps
0 #T