from lib import *
###################################################################
######################### Normal state ############################
###################################################################
n_spins=1
n_orbitals=2
n=43
mu=-4.1
s=0.05
delta=0.075
t=1.0
onsite_spin=np.eye(n_spins)
onsite_orbital=-mu*np.eye(n_orbitals)-s*Pauli_z+delta*Pauli_x
onsite_tensor=np.kron(onsite_spin,onsite_orbital)    

nn_spin=np.eye(n_spins)
nn_orbital=-t*np.eye(n_orbitals)
nn_tensor_x=np.kron(nn_spin,nn_orbital)
nn_tensor_y=nn_tensor_x


n_x=n_y=n
n_sites = n_x * n_y
dof = n_sites * n_spins * n_orbitals
###################################################################
########################## Impurities #############################
###################################################################
V=1.21
impurity_locations=[[0,0]] 
impurity_spin=np.eye(n_spins)
impurity_orbital=V*np.eye(n_orbitals)
impurity_tensor=np.kron(impurity_spin,impurity_orbital)
###################################################################
########################### SC state ##############################
###################################################################
Delta=0.0
SC_spin=1#1.0j*Pauli_y
SC_orbital=Delta*np.eye(n_orbitals)
SC_tensor=np.kron(SC_spin,SC_orbital)
###################################################################
############################ Energy ###############################
###################################################################
epsilon=0.1
omega_pts=401
omega_lim=10*t 
# omegas=np.linspace(-omega_lim,omega_lim,omega_pts,endpoint=True,dtype=complex)+1.0j*epsilon
omegas=np.array([0],dtype=complex)+1.0j*epsilon