1 #n_spins
1 #n_orbitals
79 #n
-3.57 #mu
0.0 #s
0.0 #delta
1.0 #t
1.21 #V
[[0,0]] #impurity_locations
1.2, 2.8, 2 #U
0.8 #phiUp
0.7 #phiDown
0.55 #Delta
0 #friction
275 #max_iterations
0.01 #eps
0, 0.5, 2 #T