2 #n_spins
1 #n_orbitals
25 #n
-2.67 #mu
0.0 #s
0.0 #delta
1.0 #t
0 #V
[[0,0]] #impurity_locations
1.2, 2.8, 6 #U
0.8 #phiUp
0.7 #phiDown
0.55 #Delta
0 #friction
40 #max_iterations
0.01 #eps
0, 0.25, 50 #T