from lib import *
####################################################################
######################## Self-consistent ###########################
####################################################################
model='tb'
lattice='multiorbital_chain'
phase='boundary_n'
mu=0
n_spins=1
n_x=15
V=0