from lib import *
####################################################################
############################# Square ###############################
####################################################################
model='tb'
n_name='n'
dos='True'
mu=3.57
t=1.0
orbitals=[[0,0,0]]
n_orbs=len(orbitals)
n_spins=1
n_x=n_y=21
n_z=1
dimensions=[n_x,n_y,n_z]
V=0
Delta_initial=0.45
phi_initial=2.085
hubbard='onsite'
U=2.8
T=0
friction=0
max_iterations=100
eps=0.001
