from lib import *
###################################################################
######################### Normal state ############################
###################################################################
n_spins=1
n_orbitals=1
n=79
n_x=n_y=n
mu=-3.57
s=0.0
delta=0.0
t=1.0

onsite_spin=-mu*np.eye(n_spins)
onsite_orbital=np.eye(n_orbitals)#-s*Pauli_z+delta*Pauli_x
onsite_tensor=np.kron(onsite_spin,onsite_orbital)    

nn_spin=np.eye(n_spins)
nn_orbital=-t*np.eye(n_orbitals)
nn_tensor=np.kron(nn_spin,nn_orbital)

n_sites = n_x * n_y
dof = n_sites * n_spins * n_orbitals
###################################################################
########################## Impurities #############################
###################################################################
V=1.21
impurity_locations=[[0,0]] 
im_spin=np.eye(n_spins)
im_orbital=V*np.eye(n_orbitals)
im_tensor=np.kron(im_spin,im_orbital)
###################################################################
######################### Interaction #############################
###################################################################
U=1.2
U_orbital = np.eye(n_orbitals)
U_spin = np.eye(n_spins) #Pauli_x
Hubbard_tensor = -U*np.kron(np.eye(n_sites), np.kron( U_spin, U_orbital))
###################################################################
######################### Mean-field ##############################
###################################################################
phi = 0.8

Fock = np.zeros([n_x,n_y,n_spins,n_spins,n_orbitals,n_orbitals])

Hartree = -phi*np.ones([n_x,n_y,n_spins,n_orbitals])

Gorkov= np.zeros([n_x,n_y,n_spins,n_spins,n_orbitals,n_orbitals])

friction=0.0
max_iterations=275
eps=0.01
T=0
###################################################################
############################ Energy ###############################
###################################################################
Include_DOS=True
epsilon=0.1
omega_pts=401
omega_lim=10*t 
# omegas=np.linspace(-omega_lim,omega_lim,omega_pts,endpoint=True,dtype=complex)+1.0j*epsilon
omegas=np.array([0],dtype=complex)+1.0j*epsilon