model='sc'
mu=-3.67
t=1.0
orbitals=[[0,0]]
n_orbs=len(orbitals)
hoppings = [[t, 0, 0, [1,0]],
            [t, 0, 0, [0,1]]]
n_spins=2
n_x=5
n_y=5
n_z=1
dimensions=[n_x,n_y,n_z]
V=1.21
Delta=2.5#0.03342709
phi=0#2#0.0272775
hubbard='onsite'
#hubbard='nn'
U=2.8
T=0
friction=0
max_iterations=100
eps=0.001
