This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./phd_thesis_twosided.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file phd_thesis_twosided.acn....done (14 entries accepted, 0 rejected).
Sorting entries....done (51 comparisons).
Generating output file phd_thesis_twosided.acr....done (39 lines written, 0 warnings).
Output written in phd_thesis_twosided.acr.
Transcript written in phd_thesis_twosided.alg.
