from lib import *
####################################################################
############################# Square ###############################
####################################################################
model='tb'
dos='False'
n=3
mu=-3.57
n_spins=1
n_orbs=2
t=1.0
V=0.1
U=2.8
T=0
friction=0
max_iterations=100
eps=0.001
