from lib import *
####################################################################
############################# Square ###############################
####################################################################
model='tb'
n_x=n_y=n=3
n_z=1
n_spins=1
n_orbs=2
mu=-3.57
t=1.0
V=1.21
