from lib import *
####################################################################
######################## Self-consistent ###########################
####################################################################
model='mf'
lattice='spin_chain'
phase='large_SC_small_B'
mu=0
n_spins=2
n_x=35
V=0