from lib import *
####################################################################
######################## Self-consistent ###########################
####################################################################
model='tb'
lattice='SSH_intraorbital_nn'
phase='topological_t'
mu=0
n_spins=1
n_x=15
V=0